// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __Observer_hh__
#define __Observer_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_Observer
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_Observer
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_Observer
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE tweek

_CORBA_MODULE_BEG

#ifndef __tweek_mObserver__
#define __tweek_mObserver__

  class Observer;
  class _objref_Observer;
  class _impl_Observer;
  
  typedef _objref_Observer* Observer_ptr;
  typedef Observer_ptr ObserverRef;

  class Observer_Helper {
  public:
    typedef Observer_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_Observer, Observer_Helper> Observer_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_Observer,Observer_Helper > Observer_out;

#endif

  // interface Observer
  class Observer {
  public:
    // Declarations for this interface type.
    typedef Observer_ptr _ptr_type;
    typedef Observer_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_Observer :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    void update();

    inline _objref_Observer()  { _PR_setobj(0); }  // nil
    _objref_Observer(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_Observer();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_Observer(const _objref_Observer&);
    _objref_Observer& operator = (const _objref_Observer&);
    // not implemented

    friend class Observer;
  };

  class _pof_Observer : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_Observer() : _OMNI_NS(proxyObjectFactory)(Observer::_PD_repoId) {}
    virtual ~_pof_Observer();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_Observer :
    public virtual omniServant
  {
  public:
    virtual ~_impl_Observer();

    virtual void update() = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


_CORBA_MODULE_END



_CORBA_MODULE POA_tweek
_CORBA_MODULE_BEG

  class Observer :
    public virtual tweek::_impl_Observer,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~Observer();

    inline ::tweek::Observer_ptr _this() {
      return (::tweek::Observer_ptr) _do_this(::tweek::Observer::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_tweek
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr



inline void
tweek::Observer::_marshalObjRef(::tweek::Observer_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_Observer
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_Observer
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_Observer
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_Observer
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_Observer
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_Observer
#endif

#endif  // __Observer_hh__

